language: c

sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - RunAllRcppTests="yes"
    - CRAN="http://cran.us.r-project.org"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo add-apt-repository -y ppa:edd/misc
  - sudo apt-get update -q

install:
  ## note that we currently depend on highlight 0.4.4.1 from the PPA as 0.4.5 has issues
  - ./travis-tool.sh install_aptget libprotobuf-dev libprotoc-dev protobuf-* libcurl4-gnutls-dev
  - ./travis-tool.sh install_github thirdwing/Rcpp
  - ./travis-tool.sh install_r RCurl
  - ./travis-tool.sh install_aptget r-cran-runit r-cran-inline r-cran-rbenchmark r-cran-highlight r-cran-pkgkitten

script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

    

